export const SEARCH_DOMAINS_REQUEST = 'SEARCH_DOMAINS_REQUEST';
export const SEARCH_DOMAINS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_DOMAINS_FAILURE = 'SEARCH_DOMAINS_FAILURE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';